package rs2.net;

import java.util.Arrays;

/**
 * RuneScape's ISAAC pseudorandom number generator.
 *
 * <p>
 * ISAAC stands for Indirection, Shift, Accumulate, Add, and Count. The
 * algorithm maintains 256 integers of internal state and generates output in
 * batches of 256 integers.
 * </p>
 *
 * <p>
 * The RuneScape protocol uses ISAAC to obscure packet opcodes. It does not
 * encrypt complete packet payloads:
 * </p>
 *
 * <ul>
 * <li>Outgoing opcodes have the next ISAAC value added to them.</li>
 * <li>Incoming opcodes have the next ISAAC value subtracted from them.</li>
 * <li>Both operations retain only the lowest eight bits.</li>
 * </ul>
 *
 * <p>
 * Client and server must initialize their ciphers with corresponding seeds and
 * consume exactly one value for every encoded opcode. Consuming an extra value
 * on either side permanently desynchronizes packet decoding.
 * </p>
 *
 * <p>
 * This implementation preserves the output order of the original revision 377
 * client. Generated batches are consumed from index 255 down to index 0.
 * </p>
 *
 * <p>
 * This class exists for legacy protocol compatibility and should not be treated
 * as a modern general-purpose encryption API.
 * </p>
 *
 * @see <a href="https://burtleburtle.net/bob/rand/isaac.html"> Bob Jenkins'
 *      ISAAC specification</a>
 * @see <a href=
 *      "https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/crypto/engines/ISAACEngine.java">
 *      Bouncy Castle ISAACEngine</a>
 */
public final class IsaacCipher {

	/**
	 * Number of integers in the state and result arrays.
	 */
	private static final int SIZE = 256;

	/**
	 * Mask used to constrain indirect array lookups to {@code 0..255}.
	 */
	private static final int MASK = SIZE - 1;

	/**
	 * Fractional part of the golden ratio scaled to 32 bits.
	 *
	 * <p>
	 * This constant is specified by ISAAC's initialization procedure.
	 * </p>
	 */
	private static final int GOLDEN_RATIO = 0x9e3779b9;

	/**
	 * Output generated by the most recent ISAAC round.
	 */
	private final int[] results = new int[SIZE];

	/**
	 * ISAAC's persistent internal state.
	 */
	private final int[] memory = new int[SIZE];

	/**
	 * Number of unread integers remaining in {@link #results}.
	 */
	private int valuesRemaining;

	/**
	 * ISAAC's accumulator, conventionally named {@code a}.
	 */
	private int accumulator;

	/**
	 * Previous generated result, conventionally named {@code b}.
	 */
	private int lastResult;

	/**
	 * Round counter, conventionally named {@code c}.
	 */
	private int counter;

	/**
	 * Creates and initializes an ISAAC cipher.
	 *
	 * <p>
	 * RuneScape normally supplies four integers produced during the login
	 * handshake. ISAAC itself supports up to 256 seed integers; unspecified
	 * positions are initialized to zero.
	 * </p>
	 *
	 * @throws NullPointerException     if the seed is null
	 * @throws IllegalArgumentException if the seed contains more than 256 integers
	 * @param seed the seed
	 */
	public IsaacCipher(int[] seed) {
		if (seed == null) {
			throw new NullPointerException("seed");
		}

		if (seed.length > SIZE) {
			throw new IllegalArgumentException("ISAAC accepts at most 256 seed integers: " + seed.length);
		}

		System.arraycopy(seed, 0, results, 0, seed.length);
		initialize();
	}

	/**
	 * Returns the next value in the ISAAC sequence.
	 *
	 * <p>
	 * When the current output batch is exhausted, another 256 values are generated.
	 * Values are returned in reverse array order to preserve the original client's
	 * protocol sequence.
	 * </p>
	 *
	 * @return next 32-bit ISAAC value
	 */
	public int nextInt() {
		if (valuesRemaining == 0) {
			generate();
			valuesRemaining = SIZE;
		}

		return results[--valuesRemaining];
	}

	/**
	 * Generates the next batch of 256 results.
	 *
	 * <p>
	 * Java integer overflow is intentional here. ISAAC defines its arithmetic using
	 * 32-bit words, and Java's overflowing {@code int} operations provide the
	 * required modulo-2<sup>32</sup> behavior.
	 * </p>
	 */
	private void generate() {
		lastResult += ++counter;

		for (int index = 0; index < SIZE; index++) {
			int value = memory[index];

			switch (index & 3) {
			case 0:
				accumulator ^= accumulator << 13;
				break;

			case 1:
				accumulator ^= accumulator >>> 6;
				break;

			case 2:
				accumulator ^= accumulator << 2;
				break;

			case 3:
				accumulator ^= accumulator >>> 16;
				break;

			default:
				// index & 3 is always in the range 0..3.
				throw new AssertionError();
			}

			accumulator += memory[(index + 128) & MASK];

			int mixed = memory[(value >>> 2) & MASK] + accumulator + lastResult;

			memory[index] = mixed;
			lastResult = memory[(mixed >>> 10) & MASK] + value;
			results[index] = lastResult;
		}
	}

	/**
	 * Expands the supplied seed into ISAAC's complete internal state.
	 *
	 * <p>
	 * Initialization consists of:
	 * </p>
	 *
	 * <ol>
	 * <li>Four unseeded mixing rounds.</li>
	 * <li>A pass mixing the supplied seed into the state.</li>
	 * <li>A second pass causing every seed bit to affect the full state.</li>
	 * <li>Generation of the first output batch.</li>
	 * </ol>
	 */
	private void initialize() {
		int[] mixState = new int[8];
		Arrays.fill(mixState, GOLDEN_RATIO);

		for (int round = 0; round < 4; round++) {
			mix(mixState);
		}

		// First pass: incorporate the supplied seed.
		for (int offset = 0; offset < SIZE; offset += 8) {
			for (int index = 0; index < 8; index++) {
				mixState[index] += results[offset + index];
			}

			mix(mixState);
			System.arraycopy(mixState, 0, memory, offset, 8);
		}

		// Second pass: make every seed bit affect the complete state.
		for (int offset = 0; offset < SIZE; offset += 8) {
			for (int index = 0; index < 8; index++) {
				mixState[index] += memory[offset + index];
			}

			mix(mixState);
			System.arraycopy(mixState, 0, memory, offset, 8);
		}

		generate();
		valuesRemaining = SIZE;
	}

	/**
	 * Performs ISAAC's eight-word avalanche mixing operation.
	 *
	 * @param values the values
	 */
	private static void mix(int[] values) {
		values[0] ^= values[1] << 11;
		values[3] += values[0];
		values[1] += values[2];

		values[1] ^= values[2] >>> 2;
		values[4] += values[1];
		values[2] += values[3];

		values[2] ^= values[3] << 8;
		values[5] += values[2];
		values[3] += values[4];

		values[3] ^= values[4] >>> 16;
		values[6] += values[3];
		values[4] += values[5];

		values[4] ^= values[5] << 10;
		values[7] += values[4];
		values[5] += values[6];

		values[5] ^= values[6] >>> 4;
		values[0] += values[5];
		values[6] += values[7];

		values[6] ^= values[7] << 8;
		values[1] += values[6];
		values[7] += values[0];

		values[7] ^= values[0] >>> 9;
		values[2] += values[7];
		values[0] += values[1];
	}
}
